import tkinter as tk
from tkinter import messagebox
import json

# دالة لحفظ الملاحظات
def save_note():
    note = text_box.get("1.0", tk.END).strip()
    if note:
        with open("notes.json", "w") as file:
            json.dump({"note": note}, file)
        messagebox.showinfo("حفظ", "تم حفظ الملاحظة بنجاح!")
    else:
        messagebox.showwarning("تحذير", "يرجى إدخال ملاحظة")

# دالة لفتح الملاحظة
def load_note():
    try:
        with open("notes.json", "r") as file:
            
